const colors = require("tailwindcss/colors");
/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    colors: {
      transparent: "transparent",
      current: "currentColor",
      "main-background": "hsl(222, 26%, 31%)",
      "keypad-background": "hsl(223, 31%, 20%)",
      "screen-background": "hsl(224, 36%, 15%)",
      "key-background-blue": "hsl(225, 21%, 49%)",
      "key-shadow": "hsl(224, 28%, 35%)",
      "key-background-toggle": "hsl(6, 63%, 50%)",
      "key-shadow-red": "hsl(6, 70%, 34%)",
      "key-background-orange": "hsl(30, 25%, 89%)",
      "key-shadow-orange": "hsl(28, 16%, 65%)",
      "very-dark-grayish-blue": "hsl(221, 14%, 31%)",
      "Very-dark-violet-main-background": "hsl(268, 75%, 9%)",
      "Very-dark-violet-toggle-background-keypad-background-screen-background":
        "hsl(268, 71%, 12%)",
      "Dark-violet-key-background-3": "hsl(281, 89%, 26%)",
      "Vivid-magenta-key-shadow-3": "hsl(285, 91%, 52%)",
      "Pure-cyan-key-background-toggle-3": "hsl(176, 100%, 44%)",
      "Soft-cyan-key-shadow-3": "hsl(177, 92%, 70%)",
      "Very-dark-violet-key-background-3": "hsl(268, 47%, 21%)",
      "Dark-magenta-key-shadow-3": "hsl(290, 70%, 36%)",
      "Light-yellow-3": "hsl(52, 100%, 62%)",
      "Very-dark-blue-3": "hsl(198, 20%, 13%)",
      white: "hsl(0, 0%, 100%)",
      red: colors.red,
      teal: colors.teal,
      orange: colors.orange,
      stone: colors.stone,
      gray: colors.gray,
      purple: colors.purple,
      yellow: colors.yellow,
      violet: colors.violet,
    },
    extend: {},
  },
  plugins: [],
};
